image: python:3.7

before_script:
  - apt-get update

test:
  script:
  - pip install .
  - pip install nox
  - nox --sessions tests


lint:
  script:
    - pip install nox
    - nox --sessions cop


bandit:
  script:
    - pip install nox
    - nox --sessions bandit


pages:
  stage: deploy
  script:
  - pip install .[dev]
  - cd docs
  - make html
  - cd ..
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
