"""first

Revision ID: 0bff882e822c
Revises: 
Create Date: 2020-08-14 18:10:12.347365

"""
from alembic import op
from soam.data_models import Identity
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0bff882e822c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "soam_runs",
        sa.Column("id", Identity(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=True),
        sa.Column("end_datetime", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "steps_runs",
        sa.Column("id", Identity(), nullable=False),
        sa.Column("params", sa.Text(), nullable=False),
        sa.Column("params_hash", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum("e", "pre", "f", "post", "c", name="steptypeenum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["soam_runs.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "forecaster_values",
        sa.Column("id", Identity(), nullable=False),
        sa.Column("step_run_id", sa.Integer(), nullable=False),
        sa.Column("forecast_date", sa.DateTime(), nullable=False),
        sa.Column("yhat", sa.Float(), nullable=False),
        sa.Column("yhat_lower", sa.Float(), nullable=True),
        sa.Column("yhat_upper", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("trend", sa.Float(), nullable=True),
        sa.Column("outlier_value", sa.Float(), nullable=True),
        sa.Column("outlier_sign", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["step_run_id"], ["steps_runs.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_run_id", "forecast_date"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecaster_values")
    op.drop_table("steps_runs")
    op.drop_table("soam_runs")
    # ### end Alembic commands ###
