"""First

Revision ID: 4f0360258d92
Revises: 
Create Date: 2020-08-21 02:34:22.133694

"""
from alembic import op
import sqlalchemy as sa

import soam


# revision identifiers, used by Alembic.
revision = '4f0360258d92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soam_runs',
    sa.Column('id', soam.data_models.Identity(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soam_runs_run_id'), 'soam_runs', ['run_id'], unique=True)
    op.create_table('steps_runs',
    sa.Column('id', soam.data_models.Identity(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('params_hash', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('extract', 'preprocess', 'forecast', 'postprocess', 'custom', name='steptypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['soam_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('forecaster_values',
    sa.Column('id', soam.data_models.Identity(), nullable=False),
    sa.Column('step_run_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('yhat', sa.Float(), nullable=False),
    sa.Column('yhat_lower', sa.Float(), nullable=True),
    sa.Column('yhat_upper', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('trend', sa.Float(), nullable=True),
    sa.Column('outlier_value', sa.Float(), nullable=True),
    sa.Column('outlier_sign', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['step_run_id'], ['steps_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_run_id', 'forecast_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecaster_values')
    op.drop_table('steps_runs')
    op.drop_index(op.f('ix_soam_runs_run_id'), table_name='soam_runs')
    op.drop_table('soam_runs')
    # ### end Alembic commands ###
