"""First

Revision ID: 8dd281cbc4f6
Revises: 
Create Date: 2020-08-03 19:03:27.493802

"""
from alembic import op
import sqlalchemy as sa

import soam

# revision identifiers, used by Alembic.
revision = "8dd281cbc4f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coseries_runs",
        sa.Column("id", soam.data_models.Identity(), nullable=False),
        sa.Column("params", sa.Text(), nullable=False),
        sa.Column("params_hash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forecaster_runs",
        sa.Column("id", soam.data_models.Identity(), nullable=False),
        sa.Column("params", sa.Text(), nullable=False),
        sa.Column("params_hash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "coseries_dimensions",
        sa.Column("id", soam.data_models.Identity(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=False),
        sa.Column("y_col", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["coseries_runs.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forecaster_values",
        sa.Column("id", soam.data_models.Identity(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("forecast_date", sa.DateTime(), nullable=False),
        sa.Column("yhat", sa.Float(), nullable=False),
        sa.Column("yhat_lower", sa.Float(), nullable=True),
        sa.Column("yhat_upper", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("trend", sa.Float(), nullable=True),
        sa.Column("outlier_value", sa.Float(), nullable=True),
        sa.Column("outlier_sign", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["forecaster_runs.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "forecast_date"),
    )
    op.create_table(
        "coseries_scores",
        sa.Column("id", soam.data_models.Identity(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column("analysis_datetime", sa.DateTime(), nullable=False),
        sa.Column("score_value", sa.Float(), nullable=False),
        sa.Column("spearman_value", sa.Float(), nullable=False),
        sa.Column("dtw_value", sa.Float(), nullable=False),
        sa.Column("kullback_liebler_value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["dimension_id"], ["coseries_dimensions.id"],),
        sa.ForeignKeyConstraint(["run_id"], ["coseries_runs.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "dimension_id", "analysis_datetime"),
    )
    op.create_table(
        "coseries_values",
        sa.Column("id", soam.data_models.Identity(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column("value_datetime", sa.DateTime(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["dimension_id"], ["coseries_dimensions.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dimension_id", "value_datetime"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coseries_values")
    op.drop_table("coseries_scores")
    op.drop_table("forecaster_values")
    op.drop_table("coseries_dimensions")
    op.drop_table("forecaster_runs")
    op.drop_table("coseries_runs")
    # ### end Alembic commands ###
