#act pull_request  -j build-deploy 

name: Integration workflow - validation & testing

run-name: ${{github.repository}} is getting updated by ${{github.actor}} 

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  PIP_CACHE_DIR: ${{github.workspace}}/.cache/pip
  PRE_COMMIT_HOME: ${{github.workspace}}/.cache/pre-commit
  POSTGRES_DB: soam_db
  POSTGRES_USER: soam_usr
  POSTGRES_PASSWORD: soam_pass
  TEST_DB_CONNSTR: "postgresql://soam_usr:soam_pass@postgres:5432/soam_db"

jobs:
  validate:
    runs-on: ubuntu-latest
    container: python:3.8.5
    if:  github.event_name == 'pull_request'
    env:
      TARGET_BRANCH: ${{ github.base_ref }}
      HEAD_BRANCH: ${{ github.head_ref }}
    steps:
    - uses: actions/checkout@v3
    - name: New Version Check
      run: |
        pip install packaging
        git fetch origin $HEAD_BRANCH
        git fetch origin $TARGET_BRANCH
        lib_ver=$(git diff origin/$HEAD_BRANCH origin/$TARGET_BRANCH -- soam/__init__.py | grep __version__ | cut -d = -f 2 | xargs) 
        python -c "import sys; from packaging import version; exit(not version.parse(sys.argv[1]) > version.parse(sys.argv[2]))" $lib_ver

    - name: Check changelog
      run: |
        git fetch origin $HEAD_BRANCH
        git fetch origin $TARGET_BRANCH      
        added_lines=$(git diff --numstat origin/$TARGET_BRANCH  origin/$HEAD_BRANCH -- CHANGELOG.md | awk '{print $1}')
        if [ -z $added_lines ] || [ $added_lines -eq 0 ]; then echo "Changelog has not been modified" && exit 1; else echo "Changelog has been modified" && exit 0; fi;

  test_stage:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: python:3.8.5
      options: --user root
    steps:
    - uses: actions/checkout@v3

    - name: Installing sudo package
      run: apt update && apt install sudo
      
    - name: Installing Nox
      run: pip install -U nox 

    - name: Tests
      run: |
        sudo apt-get install -y libpoppler-cpp-dev libpoppler-dev poppler-utils
        pip install pdftotext
        nox --sessions tests
    
    - name: Lint
      run: nox --sessions lint
    
    - name: DocString Coverage
      run: |
        pip install interrogate
        interrogate soam -c pyproject.toml -vv
    
    - name: Bandit
      run: nox --sessions bandit
    
    - name: Pyreverse
      run: |
        apt-get -qq update
        apt-get -qq install -y graphviz
        nox --sessions pyreverse


