name: Integration workflow - validation & testing

run-name: ${{github.repository}} is getting updated by ${{github.actor}} 

on:
  pull_request:
    branches:
      - main
      - master

env:
  PIP_CACHE_DIR: ${{github.workspace}}/.cache/pip
  PRE_COMMIT_HOME: ${{github.workspace}}/.cache/pre-commit
  POSTGRES_DB: soam_db
  POSTGRES_USER: soam_usr
  POSTGRES_PASSWORD: soam_pass
  TEST_DB_CONNSTR: "postgresql://soam_usr:soam_pass@postgres:5432/soam_db"

jobs:
  setup:
    runs-on: ubuntu-latest
    container: python:3.8.5
    steps:
    - name: Cache Nox
      uses: actions/cache@v3
      with:
        path: |
          .nox/
          .cache/pip
          apt-cache/
          ${PRE_COMMIT_HOME}
    
    - name: Running Configuration
      run: |
        export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
        apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" upgrade -y
        apt-get install texlive-xetex texlive-fonts-recommended libpoppler-cpp-dev -y
    
    - name: Installing Nox
      run: pip install nox 

  validate:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: Check version
      run: |
        pip install packaging
        git fetch origin ${{github.head_ref}}
        git fetch origin ${{github.base_ref}}
        lib_ber=$(git diff origin/${{github.head_ref}}/${{github.base_ref}})
        python -c "import sys; prom packaging import version; exit(not version.parse(sys.argv[1]) > version.parse(sys.argv[2]))" $lib_ver
        exit_status=$?
        if [ $exit_status -eq 1 ]; then echo "Error comparing versions"; fi;
        exit $exit_status
    
    - name: Check changelog
      run: |
        git fetch origin ${{github.head_ref}}
        git fetch origin ${{github.base_ref}}      
        added_lines=$(git diff --numstat origin/${{github.base_ref}}  origin/${{github.head_ref}} -- CHANGELOG.md | awk '{print $1}')
        if [ -z $added_lines ] || [ $added_lines -eq 0 ]; then echo "Changelog has not been modified" && exit 1; else echo "Changelog has been modified" && exit 0; fi;

  test_stage:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
    - name: Tests
      run: nox --sessions tests
    
    - name: Lint
      run: nox --sessions lint
    
    - name: DocString Coverage
      run: |
        pip install interrogate
        interrogate soam -c pyproject.toml -vv
    
    - name: Bandit
      run: nox --sessions bandit
    
    - name: Pyreverse
      run: |
        apt-get -qq update
        apt-get -qq install -y graphviz
        nox --sessions pyreverse


